language: elixir

elixir:
  - '1.5'
otp_release:
  - '20.1'

env:
  - MIX_ENV=test

script: mix coveralls.travis

before_deploy: mix docs

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  local_dir: doc
  skip_cleanup: true
  on:
    branch: master
